### PR TITLE
added myzigzagart app

### PR DESCRIPTION
**Pull request by myflashlab**

### CODE REVIEW

**Review by marchbold — CHANGES_REQUESTED** [review]
preview image filename is incorrect

**Comment by myflashlab** [comment]
@marchbold Thanks. I wonder if there's a time schedule for merging to master before stuff goes to the live webApp?

**Comment by marchbold** [comment]
Normally I merge them straight away but was just going through some of these other changes beforehand this round. Will have them in this week sometime.

**Comment by myflashlab** [comment]
Hi! Just noticed that this is not yet merged...

**Comment by marchbold** [comment]
Yes, this has been merged and is live.

**Comment by myflashlab** [comment]
Hmm, But I'm not seeing it here: https://airsdk.dev/showcase

**Comment by marchbold** [comment]
Its' definitely there: 
Screenshot 2023-06-09 at 7 49 23 pm

**Pull request merged**
